substitutions:
  _REGION: us-central1
  _SERVICE_NAME: cloud-run-demo
  _REPOSITORY: cloud-run-demo

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - src/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA

  - name: gcr.io/cloud-builders/docker
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --update-env-vars
      - APP__ENV=dev,APP_VERSION=$SHORT_SHA

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
